Repository dtd1232/2024-1-Sirius-Project, pull requests merged in 2024-05, with the labels that each got.

#27 [FEAT]화면전환추가
  Assets/Scenes/DH/Main.unity
  Assets/Scenes/DH/Main.unity.meta
  Assets/Scenes/DH/Options.unity
  Assets/Scenes/DH/Options.unity.meta
  Assets/Scenes/DH/Select_chr.unity
  Assets/Scenes/DH/Select_chr.unity.meta
  Assets/Scripts/DH/SceneSwitcher.cs
  Assets/Scripts/DH/SceneSwitcher.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: 💻 feat, 🍭 도현

#28 [FEAT#26] 현재 입력 / 사용 가능한 플레이어 행동 전체 UI로 표기
  Assets/Resources/Prefabs/Minuck/Available Player Behaviors Panel.prefab
  Assets/Resources/Prefabs/Minuck/Available Player Behaviors Panel.prefab.meta
  Assets/Scenes/Minuck/MinuckSampleScene2.unity
  Assets/Scripts/Minuck/InputCheckerScript.cs
  Assets/Scripts/Minuck/InputCheckerScript.cs.meta
  Assets/Scripts/Minuck/Obstacle/AvailablePlayerBehaviorsScript.cs
  Assets/Scripts/Minuck/Obstacle/AvailablePlayerBehaviorsScript.cs.meta
  Assets/Scripts/Minuck/Obstacle/ObstacleManager.cs
  Assets/Scripts/Minuck/Obstacle/ObstacleManager.cs.meta
Labels: 💻 feat, 🥟 민욱

#22 [Feat#20] 플레이어 자동 이동과 입력에 따른 행동 변화
  Assets/Scenes/YoonHajun/2024.04.07.unity.meta
  Assets/Scenes/YoonHajun/Main.unity
  Assets/Scenes/YoonHajun/Main.unity.meta
  Assets/Scenes/YoonHajun/YoonHajun_Scene.unity
  Assets/Scripts/DH/inputHandling.cs
  Assets/Scripts/YoonHajun/Jump.cs
  Assets/Scripts/YoonHajun/Jump.cs.meta
  Assets/Scripts/YoonHajun/Player.cs
  Assets/Scripts/YoonHajun/Slide.cs
  Assets/Scripts/YoonHajun/Slide.cs.meta
  ProjectSettings/TagManager.asset
Labels: 💻 feat, 🦆 하준

#34 [Feat] 스테이지 구성
  Assets/Scenes/KH/KH_Scene.unity
  Assets/Scenes/KH/PBarScene.unity
  Assets/Scenes/KH/PBarScene.unity.meta
  Assets/Scripts/KH/LongerCoin.cs
  Assets/Scripts/KH/TimerController.cs
  Assets/Scripts/KH/TimerController.cs.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: 💻 feat, 🤖 건희

#33 [FIX] inputhandler.cs 수정
  Assets/Scripts/DH/SceneSwitcher.cs
  Assets/Scripts/DH/inputHandling.cs
Labels: 🛠️ fix, 🍭 도현

#30 [FIX] 선택지 시스템 수정
  Assets/Scenes/KH/OptionUI.unity
  Assets/Scripts/KH/Data.meta
  Assets/Scripts/KH/Data/OptionA.asset
  Assets/Scripts/KH/Data/OptionA.asset.meta
  Assets/Scripts/KH/Data/OptionB.asset
  Assets/Scripts/KH/Data/OptionB.asset.meta
  Assets/Scripts/KH/Data/OptionC.asset
  Assets/Scripts/KH/Data/OptionC.asset.meta
  Assets/Scripts/KH/MainUI.cs
  Assets/Scripts/KH/OpType.cs
  Assets/Scripts/KH/Option.cs
  Assets/Scripts/KH/Option.cs.meta
  Assets/Scripts/KH/OptionData.cs
  Assets/Scripts/KH/OptionData.cs.meta
Labels: 🛠️ fix, 🤖 건희
